cc_binary(
  name = 'example',
  srcs = ['example.cpp'],
  deps = [
    '@com_baidu_babylon//:future',
    '@com_baidu_babylon//:logging',
  ],
)

cc_binary(
  name = 'anyflow_multi_nodes',
  srcs = ['anyflow_multi_nodes.cpp'],
  deps = [
    '@com_baidu_babylon//:anyflow',
  ],
)
