workspace(name = 'example')

load('@bazel_tools//tools/build_defs/repo:http.bzl', 'http_archive')

################################################################################
# babylon
http_archive(
  name = 'com_baidu_babylon',
  urls = ['https://github.com/baidu/babylon/releases/download/v1.4.3/v1.4.3.tar.gz'],
  strip_prefix = 'babylon-1.4.3',
  sha256 = '88c2b933a5d031ec7f528e27f75e3904f4a0c63aef8f9109170414914041d0ec',
)
################################################################################

################################################################################
# copy from WORKSPACE of babylon
http_archive(
  name = 'com_google_absl',
  urls = ['https://github.com/abseil/abseil-cpp/archive/refs/tags/20220623.1.tar.gz'],
  strip_prefix = 'abseil-cpp-20220623.1',
  sha256 = '91ac87d30cc6d79f9ab974c51874a704de9c2647c40f6932597329a282217ba8',
)

http_archive(
  name = 'com_google_protobuf',
  urls = ['https://github.com/protocolbuffers/protobuf/archive/refs/tags/v3.19.6.zip'],
  strip_prefix = 'protobuf-3.19.6',
  sha256 = '387e2c559bb2c7c1bc3798c4e6cff015381a79b2758696afcbf8e88730b47389',
)
load('@com_google_protobuf//:protobuf_deps.bzl', 'protobuf_deps')
protobuf_deps()

http_archive(
  name = 'com_github_nelhage_rules_boost',
  urls = ['https://github.com/nelhage/rules_boost/archive/4ab574f9a84b42b1809978114a4664184716f4bf.tar.gz'],
  strip_prefix = 'rules_boost-4ab574f9a84b42b1809978114a4664184716f4bf',
  sha256 = '2215e6910eb763a971b1f63f53c45c0f2b7607df38c96287666d94d954da8cdc',
)
load('@com_github_nelhage_rules_boost//:boost/boost.bzl', 'boost_deps')
boost_deps()

http_archive(
  name = 'fmt',
  urls = ['https://github.com/fmtlib/fmt/archive/refs/tags/8.1.1.tar.gz'],
  strip_prefix = 'fmt-8.1.1',
  sha256 = '3d794d3cf67633b34b2771eb9f073bde87e846e0d395d254df7b211ef1ec7346',
  build_file = "@com_baidu_babylon//bazel/fmt:BUILD.bazel",
)
################################################################################
