name: example

on:
  push:
    branches: [main]

jobs:
  basic:
    strategy:
      matrix:
        name:
        - anyflow
        - depend-use-bzlmod
        - depend-use-cmake-fetch
        - depend-use-cmake-find
        - depend-use-cmake-subdir
        - depend-use-workspace
        - use-arena-with-brpc
        - use-async-logger
        - use-counter-with-bvar
        - use-with-bthread
        - use-with-glog
    runs-on: ubuntu-latest
    name: ${{matrix.name}}
    steps:
    - uses: actions/checkout@v4
    - if: ${{matrix.name == 'depend-use-cmake-find'}}
      run: |
        sudo apt install libabsl-dev
        sudo apt install libboost-all-dev
        sudo apt install libprotobuf-dev
    - run: cd example/${{matrix.name}} && ./build.sh
